export const CHECKOUT_TYPES = {
  FIRST_NAME: 'FIRST_NAME',
  LAST_NAME: 'LAST_NAME',
  COMPANY_NAME: 'COMPANY_NAME',
  STREET_ADRESS: 'STREET_ADRESS',
  REGION: 'REGION',
  STATES: 'STATES',
  ZIP_CODE: 'ZIP_CODE',
  EMAIL: 'EMAIL',
  PHONE: 'PHONE',
  SHIP_TO_DIFFERENT_ADRESS: 'SHIP_TO_DIFFERENT_ADRESS',
  ADDITIONAL_INFO: 'ADDITIONAL_INFO',
}
